#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 
bspc monitor -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr &
setxkbmap -model abnt2 -layout br -variant abnt2
${HOME}/monitor.sh
nitrogen --restore
${HOME}/Scripts/exec-xterm
polybar &
bspc config normal_border_color "#FF0000"
bspc config focused_border_color "#FFFF00"
bspc config presel_feedback_color “#008000”
bspc config focus_follows_pointer true
bspc monitor LVDS-1 -d  1 2 3 4 5 6 7 8 9 10

